version: '3.7'
services: 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secondphp
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9002:9000"
  mysql:
    image: mysql:5.7
    container_name: secondmysql
    ports:
      -  "33062:3306"
    volumes:
      -  ./db:/var/lib/mysql
      -  ./my_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
  nginx:
    image: nginx:stable-alpine
    container_name: secondnginx
    ports:
      -  "8090:80"
    volumes:
      -  ./src:/var/www/html
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -  php
      -  mysql